-- AlterTable
ALTER TABLE "public"."Availability" ALTER COLUMN "startTime1" SET DATA TYPE TIME,
ALTER COLUMN "endTime1" SET DATA TYPE TIME,
ALTER COLUMN "startTime2" SET DATA TYPE TIME,
ALTER COLUMN "endTime2" SET DATA TYPE TIME,
ALTER COLUMN "startTime3" SET DATA TYPE TIME,
ALTER COLUMN "endTime3" SET DATA TYPE TIME;
